### ISSUE TITLE
Merge into upstream

### ISSUE THREAD

**Issue by kuwv** [appsecco/owasp-threat-dragon-gitlab#3]
@makash @riyazwalikar

Do you have objections to merging this work back into the upstream for other users of Threat Dragon? I can probably do it myself but I'd like to get your approval first.

https://github.com/OWASP/threat-dragon/issues/9

**Comment by jgadsden** [comment]
@kuwv I have given you some more permissions on the Threat Dragon repo, and can assign https://github.com/OWASP/threat-dragon/issues/9 to you once you accept

Personally I think you should go ahead with this work, it would be really good to have this

**Comment by kuwv** [comment]
Too divergent. Closing.
